name: Deploy Hello World App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn clean package

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.0.0  # Specify the Terraform version you want to use

      - name: Terraform Init
        run: terraform init
        working-directory: terraform

      - name: Terraform Apply
        env:
          TF_VAR_key_name: ${{ secrets.EC2_KEY_NAME }}  # Add the key name to your secrets
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: terraform apply -auto-approve
        working-directory: terraform

      - name: Get EC2 Public IP
        id: get_ip
        run: |
          PUBLIC_IP=$(terraform output -raw public_ip | tr -d '\r\n')       
          echo "EC2_HOST=$(terraform output -raw public_ip)" >> $GITHUB_ENV
        working-directory: terraform

      - name: Copy JAR to EC2
        env:
          EC2_USER: ${{ secrets.EC2_USER }}
          EC2_KEY: ${{ secrets.EC2_KEY }}
        run: |
          scp -i $EC2_KEY target/*.jar $EC2_USER@$EC2_HOST:/home/$EC2_USER/hello-world-app.jar

      - name: Run the application on EC2
        env:
          EC2_USER: ${{ secrets.EC2_USER }}
          EC2_KEY: ${{ secrets.EC2_KEY }}
        run: |
          ssh -i $EC2_KEY $EC2_USER@$EC2_HOST "nohup java -jar /home/$EC2_USER/hello-world-app.jar > /dev/null 2>&1 &"
